-- Table City

CREATE TABLE CITY (ID INT AUTO_INCREMENT PRIMARY KEY, NAME VARCHAR(20) NOT NULL, COUNTRYCODE VARCHAR(5) NOT NULL,
DISTRICT VARCHAR(20) NOT NULL, POPULATION INT NOT NULL);

-- Solutions to HackerRank Question

SELECT NAME FROM CITY
WHERE POPULATION > 120000 AND COUNTRYCODE = 'USA';

SELECT * FROM CITY;

SELECT * FROM CITY
WHERE ID = 1661;

SELECT * FROM CITY
WHERE COUNTRYCODE = 'JPN';

-- Table Station

CREATE TABLE STATION (ID INT AUTO_INCREMENT PRIMARY KEY, CITY VARCHAR(20) NOT NULL, STATE VARCHAR(20) NOT NULL,
  LAT_N INT NOT NULL, LONG_W INT NOT NULL);

-- Solutions to HackerRank Question

SELECT DISTINCT CITY FROM STATION
WHERE ID % 2 = 0;

SELECT COUNT(*) - COUNT(DISTINCT(CITY)) FROM STATION;

(
SELECT CITY, LENGTH(CITY) FROM STATION
WHERE LENGTH(CITY) = (SELECT MIN(LENGTH(CITY)) FROM STATION)
ORDER BY CITY
LIMIT 1
)
UNION ALL
(
SELECT CITY, LENGTH(CITY) FROM STATION
WHERE LENGTH(CITY) = (SELECT MAX(LENGTH(CITY)) FROM STATION)
ORDER BY CITY
LIMIT 1
);

SELECT CITY FROM STATION
WHERE CITY REGEXP '^[aeiou]';

SELECT DISTINCT CITY FROM STATION
WHERE CITY REGEXP '[aeiou]$';

SELECT CITY FROM STATION
WHERE CITY REGEXP '^[aeiou]'
AND CITY REGEXP '[aeiou]$';

SELECT DISTINCT CITY FROM STATION
WHERE CITY NOT REGEXP '^[aeiou]';

SELECT DISTINCT CITY FROM STATION
WHERE CITY NOT REGEXP '[aeiou]$';

